from .UserOrderListViews import UserOrderListView
from .OrderDetailAPIViews import OrderDetailAPIView
from .CreateReturnRequestViews import CreateReturnRequestView
from .ReturnRequestAdminListUpdateViews import ReturnRequestAdminListUpdateAPIView
from .CreateOrderViews import CreateOrderView
from .AdminUpdateOrderStatusViews import AdminUpdateOrderStatusAPIView
from .AdminOrderView import AdminOrderDetailAPIView , AdminOrderListAPIView
from .AdminReturnRequestViews import AdminReturnRequestAPIView
from .AdminOrderReportViews import AdminOrderReportAPIView
from .AdminOrderReportPDFViews import AdminOrderReportPDFAPIView
from .SalesReportViews import SalesReportAPIView